from routes.auth_routes import router as auth_router
from routes.document_routes import router as document_router
from routes.chat_routes import router as chat_router
from routes.generator_routes import router as generator_router
from routes.lawyer_routes import router as lawyer_router
from routes.forum_routes import router as forum_router
from routes.news_routes import router as news_router
from routes.user_routes import router as user_router
from routes.appointment_routes import router as appointment_router
from routes.notification_routes import router as notification_router
from routes.direct_chat_routes import router as direct_chat_router
from routes.ml_routes import router as ml_router
