name: Deploy Frontend to GitHub Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies & Build
        run: |
          cd frontend-web
          npm install
          CI=false npm run build
          cp build/index.html build/404.html

      - name: Deploy to gh-pages Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend-web/build
