name: Deploy Historical Test Reports to GitHub Pages

on:
  workflow_dispatch:
  push:
    paths:
      - 'reports/**'

permissions:
  contents: write

jobs:
  deploy-reports:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Reports to gh-pages Branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports
